apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
    usage: {{ .Values.service.labels.usage }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.pod.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
